P_E_13/P_E_13/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('portfolio/', include('portfolio.urls', namespace='portfolio')),
    path('article/', include('article.urls', namespace='article')),
    path('contactme/', include('contact_me.urls', namespace='contact_me')),
    # ckeditor file path
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

P_E_13/article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('', views.ArticleListView.as_view(), name='article'),
    path('detail/<int:article_id>/<slug:article_slug>/', views.ArticleDetailView.as_view(), name='detail_article'),
]

P_E_13/contact_me/urls.py
from django.urls import path
from . import views

app_name = 'contact_me'

urlpatterns = [
    path('', views.ContactMeView.as_view(), name='contact_me'),

]

P_E_13/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

P_E_13/portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.PortfolioView.as_view(), name='portfolio'),
    path('detail/<int:portfolio_id>/<slug:portfolio_slug>/', views.PortfolioDetailView.as_view(), name='detail_portfolio'),
]

P_E_13/article/models.py
from django.db import models
from django.urls import reverse


class Article(models.Model):
    image = models.ImageField(upload_to='images/blog')
    image_full = models.ImageField(upload_to='images/blog/full')
    category = models.CharField(max_length=20, blank=True, null=True)
    title = models.CharField(max_length=50)
    body = models.TextField()
    creat_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ('-creat_at',)

    def __str__(self):
        return f'{self.title} - {self.creat_at}'

    def get_absolute_url(self):
        return reverse('article:detail_article', args=(self.id, self.slug))

P_E_13/contact_me/models.py
from django.db import models


class UserContact(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField()
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-timestamp',)

    def __str__(self):
        return f'{self.name}-{self.timestamp}'

P_E_13/home/models.py
from django.db import models

# Create your models here.

P_E_13/portfolio/models.py
from django.db import models
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.translation import gettext_lazy as _


class Portfolio(models.Model):
    name = models.CharField(max_length=20)
    title = models.CharField(max_length=40)
    description = RichTextUploadingField(verbose_name=_("description"), blank=True, null=True)
    image = models.ImageField(upload_to='images/portfolio')
    image_full = models.ImageField(upload_to='images/portfolio/full', blank=True, null=True)
    video = models.FileField(upload_to='videos/portfolio', blank=True, null=True)
    creat_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ('-creat_at',)

    def __str__(self):
        return f'{self.name} - {self.creat_at}'

    def get_absolute_url(self):
        return reverse('portfolio:detail_portfolio', args=(self.id, self.slug))

P_E_13/contact_me/forms.py
from django import forms
from .models import UserContact


class UserContactForm(forms.ModelForm):
    class Meta:
        model = UserContact
        fields = '__all__'

P_E_13/article/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from article.models import Article


class ArticleListView(View):
    def get(self, request):
        articles = Article.objects.all()
        return render(request, 'article/article_list.html', {'articles': articles})


class ArticleDetailView(View):
    def get(self, request, *args, **kwargs):
        article = get_object_or_404(Article, pk=kwargs['article_id'], slug=kwargs['article_slug'])
        return render(request, 'article/detail_article.html', {'article': article})

P_E_13/contact_me/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import UserContactForm
from django.contrib import messages


class ContactMeView(View):
    def get(self, request):
        return render(request, 'contact_me/contact_me.html')

    def post(self, request):
        form = UserContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'your message was sent successfully! I reply you soon', extra_tags='success')
        else:
            messages.error(request, 'not a valid message', extra_tags='danger')
        return redirect('contact_me:contact_me')

P_E_13/home/views.py
from django.shortcuts import render
from django.views import View


class HomeView(View):
    def get(self, request):
        return render(request, 'home/index.html')

P_E_13/portfolio/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View

from portfolio.models import Portfolio


class PortfolioView(View):
    def get(self, request):
        portfolios = Portfolio.objects.all()
        return render(request, 'portfolio/portfolio_list.html', {'portfolios': portfolios})


class PortfolioDetailView(View):
    def get(self, request, *args, **kwargs):
        portfolio = get_object_or_404(Portfolio, pk=kwargs['portfolio_id'], slug=kwargs['portfolio_slug'])
        return render(request, 'portfolio/detail_portfolio.html', {'portfolio': portfolio})

P_E_13/article/templates/article/article_list.html
{% extends 'base.html' %}

{% block title %}Article List{% endblock title %}


{% block content %}

    <div id="main" class="site-main">
        <!-- Page changer wrapper -->
        <div class="pt-wrapper">
            <!-- Subpages -->
            <div class="subpages">
                <!-- Blog Subpage -->
                <section class="pt-page-current" data-id="blog">
                    <div class="section-inner custom-page-content">
                        <div class="page-header color-1">
                            <h2>Article</h2>
                        </div>
                        <div class="page-content">

                            <!-- Blog Posts Grid -->
                            <div class="blog-masonry two-columns">
                                <!-- Blog Post 1 -->
                                {% for article in articles %}
                                    <div class="item">
                                        <div class="blog-card">
                                            <div class="media-block">
                                                <a href="{{ article.get_absolute_url }}">
                                                    <img class="post-image img-responsive" src="{{ article.image.url }}" alt="" />
                                                    <div class="mask"></div>
                                                    <div class="post-date"><span class="day">{{ article.creat_at|date:"d" }}</span><span class="month">{{ article.creat_at|date:"N" }}</span><span class="year">{{ article.creat_at|date:"Y" }}</span></div>
                                                </a>
                                            </div>
                                            <div class="post-info">
                                                <ul class="category">
                                                    <li><a href="#">{{ article.category }}</a></li>
                                                </ul>
                                                <a href="{{ article.get_absolute_url }}"><h4 class="blog-item-title">{{ article.title }}</h4></a>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                                <!-- End of Blog Post 1 -->
                            </div>
                            <!-- Blog Posts Grid -->
                        </div>
                    </div>
                </section>
                <!-- /Blog Subpage -->
            </div>
        </div>
    </div>

{% endblock content %}

P_E_13/article/templates/article/detail_article.html
{% extends 'base.html' %}

{% block title %}Detail Article {% endblock title %}

{% block content %}

    <!-- Main Content -->
    <div id="main" class="site-main">
        <!-- Single Page Content -->
        <div class="single-page-content">
            <div class="content-area">
                <div class="page-content">
                    <!-- Blog Entry Content -->
                    <div class="blog-post-main-image">
                        <img class="post-image img-responsive" src="{{ article.image_full.url }}" alt=""/>
                    </div>

                    <div class="blog-post-content">
                        <h1>{{ article.title }}</h1>

                        <div class="entry-meta">
                            <span class="date"><a><i class="fa fa-fw fa-clock-o"></i>{{ article.creat_at|date:"d N, Y" }}</a></span>
                        </div>

                        <p>{{ article.body }}</p>

                        <blockquote>
                            <p>Your time is limited, so don't waste it living someone else's life. Don't be trapped by
                                dogma - which is living with the results of other people's thinking. Don't let the noise
                                of others' opinions drown out your own inner voice. And most important, have the courage
                                to follow your heart and intuition.</p>
                            <footer><cite>Steve Jobs</cite></footer>
                        </blockquote>

                        <div class="entry-meta entry-tags-share">
                            <!-- Share Buttons -->
                            {#                  <div class="btn-group share-buttons pull-right hidden-xs">#}
                            {#                    <a href="#" target="_blank" class="btn"><i class="fa fa-facebook"></i> </a>#}
                            {#                    <a href="#" target="_blank" class="btn"><i class="fa fa-twitter"></i> </a>#}
                            {#                    <a href="#" target="_blank" class="btn"><i class="fa fa-dribbble"></i> </a>#}
                            {#                  </div>#}
                            <!-- /Share Buttons -->
                            <ul class="tags">
                                <li><a>python</a></li>
                                <li><a>Django</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- End of Blog Entry Content -->
                </div>
            </div>
        </div>
        <!-- End of Single Page Content -->
    </div>

{% endblock %}

P_E_13/contact_me/templates/contact_me/contact_me.html
{% extends 'base.html' %}

{% block title %}Contact Me{% endblock title %}

{% block content %}

    <!-- Main Content -->
    <div id="main" class="site-main">
        <!-- Page changer wrapper -->
        <div class="pt-wrapper">
            <!-- Subpages -->
            <div class="subpages">
                <!-- Contact Subpage -->
                <section class="pt-page-current" data-id="contact">
                    <div class="section-inner custom-page-content">
                        <div class="page-header color-1">
                            <h2>Contact</h2>
                        </div>
                        <div class="page-content">

                            <div class="row">
                                <div class="col-sm-6 col-md-6">
                                    <div class="block-title">
                                        <h3>Get in <span>Touch</span></h3>
                                    </div>

                                    <div class="contact-info-block">
                                        <div class="ci-icon">
                                            <i class="fa fa-map-marker"></i>
                                        </div>
                                        <div class="ci-text">
                                            <h5>Tehran, IR</h5>
                                        </div>
                                    </div>
                                    <div class="contact-info-block">
                                        <div class="ci-icon">
                                            <i class="fa fa-envelope"></i>
                                        </div>
                                        <div class="ci-text">
                                            <h5>parham.esmaeili@gmail.com</h5>
                                        </div>
                                    </div>
                                    <div class="contact-info-block">
                                        <div class="ci-icon">
                                            <i class="fa fa-phone"></i>
                                        </div>
                                        <div class="ci-text">
                                            <h5>+989102179459</h5>
                                        </div>
                                    </div>
                                    <div class="contact-info-block">
                                        <div class="ci-icon">
                                            <i class="fa fa-check"></i>
                                        </div>
                                        <div class="ci-text">
                                            <h5>Freelance Available</h5>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-6 col-md-6">
                                    <div class="block-title">
                                        <h3>Contact <span>Form</span></h3>
                                    </div>

                                    <form method="post" action="">
                                        {% csrf_token %}

                                        <div class="messages"></div>

                                        <div class="controls">
                                            <div class="form-group form-group-with-icon">
                                                <i class="fa fa-user"></i>
                                                <label>Full Name</label>
                                                <input id="form_name" type="text" name="name" class="form-control" placeholder required="required" data-error="Name is required.">
                                                <div class="form-control-border"></div>
                                                <div class="help-block with-errors"></div>
                                            </div>

                                            <div class="form-group form-group-with-icon">
                                                <i class="fa fa-envelope"></i>
                                                <label>Email Address</label>
                                                <input id="form_email" type="email" name="email" class="form-control" placeholder required="required" data-error="Valid email is required.">
                                                <div class="form-control-border"></div>
                                                <div class="help-block with-errors"></div>
                                            </div>

                                            <div class="form-group form-group-with-icon">
                                                <i class="fa fa-comment"></i>
                                                <label>Message for Me</label>
                                                <textarea id="form_message" name="message" class="form-control" placeholder rows="4" required="required" data-error="Please, leave me a message."></textarea>
                                                <div class="form-control-border"></div>
                                                <div class="help-block with-errors"></div>
                                            </div>

                                            <input type="submit" class="button btn-send" value="Send message" href="{% url 'contact_me:contact_me' %}">
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- End Contact Subpage -->
                <!-- /Blog Subpage -->
                <!-- /Page changer wrapper -->
            </div>
        </div>
    </div>

{% endblock %}

P_E_13/home/templates/home/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Home {% endblock title %}

{% block content %}

    <!-- Main Content -->
    <div id="main" class="site-main">
        <!-- Page changer wrapper -->
        <div class="pt-wrapper">
            <!-- Subpages -->
            <div class="subpages">

                <!-- Home Subpage -->
                <section class="pt-page-current" data-id="home">
                    <div class="section-inner start-page-content">
                        <div class="page-header">
                            <div class="row">
                                <div class="col-sm-4 col-md-4 col-lg-4">
                                    <div class="photo">
                                        <img alt="" src="{% static 'images/ParhamEsmaeili.jpg' %}">
                                    </div>
                                </div>

                                <div class="col-sm-8 col-md-8 col-lg-8">

                                    <div class="title-block">
                                        <h1>Parham Esmaeili</h1>
                                        <div class="owl-carousel text-rotation">
                                            <div class="item">
                                                <div class="sp-subtitle">Server Website</div>
                                            </div>
                                            <div class="item">
                                                <div class="sp-subtitle">Backend-developer</div>
                                            </div>
                                        </div>
                                    </div>

                                    {#                    <div class="social-links">#}
                                    {#                      <a href="#"><i class="fa fa-twitter"></i></a>#}
                                    {#                      <a href="#"><i class="fa fa-facebook"></i></a>#}
                                    {#                      <a href="#"><i class="fa fa-instagram"></i></a>#}
                                    {#                    </div>#}
                                </div>
                            </div>
                        </div>

                        <div class="page-content">
                            <div class="row">

                                <div class="col-sm-6 col-md-6 col-lg-6">
                                    <div class="about-me">
                                        <div class="block-title">
                                            <h3>About <span>Me</span></h3>
                                        </div>
                                        <p> Hello! I’m Parham Esmaeili<br>
                                            Back End developer<br>
                                            To contact me for consultation and cooperation,<br>
                                            please send a message.</p>
                                    </div>
                                    <div class="download-resume">
                                        <a href="{% url 'contact_me:contact_me' %}" class="btn btn-secondary">Contact Me</a>
                                    </div>
                                </div>

                                <div class="col-sm-6 col-md-6 col-lg-6">
                                    <ul class="info-list">
                                        <li><span class="title">Age</span><span class="value">24</span></li>
                                        <li><span class="title">Residence</span><span class="value">IRN</span></li>
                                        <li><span class="title">Address</span><span class="value">Tehran, Iran</span></li>
                                        <li><span class="title">e-mail</span><span class="value"><a href="mailto:parham.esmaeili@gmail.com">parham.esmaeili@gmail.com</a></span></li>
                                        <li><span class="title">Phone</span><span class="value">+989102179459</span></li>
                                        <li><span class="title">Freelance</span><span class="value available">Available</span></li>
                                    </ul>
                                </div>

                            </div>
                        </div>
                    </div>
                </section>
                <!-- End of Home Subpage -->

            </div>
        </div>
        <!-- /Page changer wrapper -->
    </div>
    <!-- /Main Content -->

{% endblock %}

P_E_13/portfolio/templates/portfolio/detail_portfolio.html
{% extends 'base.html' %}

{% block title %} Portfolio Detail {% endblock title %}

{% block content %}

    <!-- Main Content -->
    <div id="main" class="site-main">
        <!-- Page changer wrapper -->
        <div class="pt-wrapper">
            <!-- Subpages -->
            <div class="subpages">

                <div class="ajax-page-title">
                    <h1>{{ portfolio.title }}</h1>
                </div>

                {% if portfolio.image_full %}
                    <div class="row">
                    <div class="col-sm-7 col-md-7 portfolio-block">
                    <div class="owl-carousel portfolio-page-carousel">
                        <div class="item">
                            <img src="{{ portfolio.image_full.url }}" alt=""/>
                        </div>
                    </div>
                {% endif %}

                {% if portfolio.video %}
                    <div class="portfolio-page-video embed-responsive embed-responsive-16by9" >
                        <video controls class="embed-responsive-item">
                            <source src="{{ portfolio.video.url }}" type='video/mp4'>
                        </video>
                    </div>
                {% endif %}

                <div class="portfolio-page-image">
                    <img src="{{ portfolio.image.url }}" alt="">
                </div>

                <script type="text/javascript">

                    jQuery(document).ready(function ($) {

                        $('.portfolio-page-carousel').owlCarousel({
                            smartSpeed: 1200,
                            items: 1,
                            loop: true,
                            dots: true,
                            nav: true,
                            navText: false,
                            margin: 10
                        });

                    });
                </script>
                </div>

                <div class="col-sm-5 col-md-5 portfolio-block">
                    <!-- Project Description -->
                    <div class="block-title">
                        <h3>Description</h3>
                    </div>
                    <ul class="project-general-info">
                        <li><p><i class="fa fa-user"></i> Parham Esmaeili</p></li>
                        <li><p><i class="fa fa-globe"></i> <a href="#" target="_blank">www.project-site.com</a></p></li>
                        <li><p><i class="fa fa-calendar"></i>{{ portfolio.creat_at|date:"d N, Y" }}</p></li>
                    </ul>
                    {# #}
                    <p class="text-justify">{{ portfolio.description|safe }}</p>
                    <!-- /Project Description -->

                    <!-- Technology -->
                    <div class="tags-block">
                        <div class="block-title">
                            <h3>Technology</h3>
                        </div>
                        <ul class="tags">
                            <li><a>python</a></li>
                            <li><a>Django</a></li>
                        </ul>
                    </div>
                    <!-- /Technology -->

                    <!-- Share Buttons -->
                    {#                    <div class="btn-group share-buttons">#}
                    {#                        <div class="block-title">#}
                    {#                            <h3>Share</h3>#}
                    {#                        </div>#}
                    {#                        <a href="#" target="_blank" class="btn"><i class="fa fa-facebook"></i> </a>#}
                    {#                        <a href="#" target="_blank" class="btn"><i class="fa fa-twitter"></i> </a>#}
                    {#                        <a href="#" target="_blank" class="btn"><i class="fa fa-dribbble"></i> </a>#}
                    {#                    </div>#}
                    <!-- /Share Buttons -->
                </div>
                </div>
                <!-- /Page changer wrapper -->
            </div>
        </div>
    </div>

{% endblock %}

P_E_13/portfolio/templates/portfolio/portfolio_list.html
{% extends 'base.html' %}

{% block title %} Portfolio list {% endblock title %}

{% block content %}

    <!-- Main Content -->
    <div id="main" class="site-main">
        <!-- Page changer wrapper -->
        <div class="pt-wrapper">
            <!-- Subpages -->
            <div class="subpages">

                <!-- Portfolio Subpage -->
                <section class="pt-page-current" data-id="portfolio">
                    <div class="section-inner custom-page-content">
                        <div class="page-header color-1">
                            <h2>Portfolio</h2>
                        </div>
                        <div class="page-content">

                            <!-- Portfolio Content -->
                            <div class="portfolio-content">

                                <!-- Portfolio Grid -->
                                <div id="portfolio_grid" class="portfolio-grid portfolio-masonry masonry-grid-3">

                                    {% for portfolio in portfolios %}
                                        <!-- Portfolio Item 1 -->
                                        <figure class="item">
                                            <a class="ajax-page-load" href="{{ portfolio.get_absolute_url }}">
                                                <img src="{{ portfolio.image.url }}" alt="">
                                                <div>
                                                    <h5 class="name">{{ portfolio.name }}</h5>
                                                    <small>more...</small>
                                                    <i class="fa fa-file-text-o"></i>
                                                </div>
                                            </a>
                                        </figure>
                                    {% endfor %}
                                    <!-- /Portfolio Item 1 -->
                                </div>
                                <!-- /Portfolio Grid -->

                            </div>
                            <!-- /Portfolio Content -->
                        </div>
                    </div>
                </section>
                <!-- /Portfolio Subpage -->
            </div>
        </div>
    </div>

{% endblock %}

P_E_13/templates/base.html
<!DOCTYPE html>
<html class="loading" lang="en-US">

    <head>
        {% include 'includes/head.html' %}
        <title>{% block title %}{% endblock title %}</title>
    </head>

    <body class="material-template">
        <!-- Loading animation -->
        <div class="preloader">
            <div class="preloader-animation">
                <div class="preloader-spinner">
                </div>
            </div>
        </div>

        {% include 'includes/navbar.html' %}
        {% include 'includes/messages.html' %}

        {% block content %} {% endblock %}

        {% include 'includes/footer.html' %}
    </body>

</html>

P_E_13/templates/includes/footer.html
{% load static %}

<footer>
    <div> <a href="https://www.x.com/"> </a> </div>
</footer>


<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/validator.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.shuffle.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/masonry.pkgd.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.hoverdir.js' %}"></script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>

P_E_13/templates/includes/navbar.html
<div class="page" id="page">
    <!-- Header -->
    <header id="site_header" class="header mobile-menu-hide">
        <div class="header-content">
            <div class="site-title-block mobile-hidden">
                <div class="site-title">Parham <span>Esmaeili</span></div>
            </div>

            <!-- Navigation -->
            <div class="site-nav">
                <!-- Main menu -->
                <ul id="nav" class="site-main-menu">
                    <li>
                        <a class="pt-trigger" href="{% url 'home:home' %}">Home</a>
                    </li>
                    <li>
                        <a class="pt-trigger" href="{% url 'portfolio:portfolio' %}">Portfolio</a>
                    </li>
                    <li>
                        <a class="pt-trigger" href="{% url 'article:article' %}">Article</a>
                    </li>
                    <li>
                        <a class="pt-trigger" href="{% url 'contact_me:contact_me' %}">Contact</a>
                    </li>
                </ul>
                <!-- /Main menu -->
            </div>
            <!-- Navigation -->
        </div>
    </header>
    <!-- /Header -->

    <!-- Mobile Header -->
    <div class="mobile-header mobile-visible">
        <div class="mobile-logo-container">
            <div class="mobile-site-title">Parham Esmaeili</div>
        </div>

        <a class="menu-toggle mobile-visible">
            <i class="fa fa-bars"></i>
        </a>
    </div>
    <!-- /Mobile Header -->
</div>